<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/09/22 14:12:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
