<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/09/23 10:56:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
